language: swift
osx_image: xcode10.2
cache:
  - bundler
  - cocoapods
xcode_workspace: ConfigurationDemo.xcworkspace
xcode_scheme: ConfigurationDemo-Release
xcode_destination: platform:iOS Simulator, id:6F17A6EA-29EC-4646-B6B4-84FF3D4FD589, OS:12.0, name:iPhone X
before_install:
  - bundle install
  - gem install linterbot
  - bundle exec pod install --repo-update
install:
  - set -o pipefail
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
  - bundle install --path=vendor/bundle --jobs 4 --retry 3
