language: swift
osx_image: xcode10.2
xcode_workspace: ConfigurationDemo.xcworkspace
xcode_scheme: ConfigurationDemo-Release
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
before_install:
  - bundle install
  - gem install linterbot
  - bundle exec pod install --repo-update
install:
  - set -o pipefail
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
  - bundle install --path=vendor/bundle --jobs 4 --retry 3
