language: Swift
osx_image: xcode10.2
cache:
  - bundler
  - cocoapods
xcode_workspace: ConfigurationDemo.xcworkspace
xcode_scheme: ConfigurationDemo-Release
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
before_install:
  - bundle install
  - gem install linterbot
  - bundle exec pod install --repo-update
install:
  - set -o pipefail
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
  - bundle install --path=vendor/bundle --jobs 4 --retry 3
before_script:
  - chmod a+x ./scripts/add-key.sh
  - sh ./scripts/add-key.sh
script:
  - ./scripts/linter
  - ./scripts/run
